version: '3'
services:
  snapcast:
    container_name: snapcast
    restart: always
    image: ghcr.io/hifiberry/extension_snapcast:0.28.0
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/snd:/dev/snd
    network_mode: host
    group_add:
      - 2001
    volumes:
      - /etc/snapcastmpris.conf:/etc/snapcastmpris.conf
      - /etc/asound.conf:/etc/asound.conf
      - /run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
